### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by jbourdale** [tom-grey/typedoc-plugin-markdown#103] opened 2019-10-07 09:13 UTC
Hello everyone,

I am trying to use your plugin to generate an API Reference that fit in docusaurus.

So, I've followed the README Installation and Usage guide but I can't figure out how to run the plugin.

I've done
`npm install --save-dev typedoc typedoc-plugin-markdow`

and then in my package.json
`"build:doc": "typedoc --module commonjs --plugin typedoc-plugin-markdown src"`
`npm run build:doc`

This didn't work, so i tried, as you suggest 
`npx typedoc --module commonjs --plugin typedoc-plugin-mardown src`

But both times i got the same result :

`Error: "typedoc-plugin-markdown" needs to be executed from the same location as "typedoc".
Please make sure to run "npx typedoc" or alternatively install the plugin globally.`

Does someone have a solution ?

typedoc version : 0.14.0
typedoc-plugin-mardown version: 2.2.7
node version: 11.10.0
npm version: 6.11.3

**Comment by tom-grey** [comment] 2019-10-07 09:39
Do you have monorepo with multiple package.json or a single package.json?

**Comment by jbourdale** [comment] 2019-10-07 09:40
I tryed on both, same result

**Comment by tom-grey** [comment] 2019-10-07 09:44
Can you please try?

```
node_modules/.bin/typedoc --module commonjs --plugin typedoc-plugin-markdown src
```

**Comment by jbourdale** [comment] 2019-10-07 09:47
I've tried that too :/ 

```
$> node_modules/.bin/typedoc --module commonjs --plugin typedoc-plugin-markdown --out docs src
Loaded plugin typedoc-plugin-markdown

Using TypeScript 3.2.4 from /Users/jbourdale/NODATA/test/node_modules/typedoc/node_modules/typescript/lib
Error: "typedoc-plugin-markdown" needs to be executed from the same location as "typedoc".
Please make sure to run "npx typedoc" or alternatively install the plugin globally.

```

**Comment by tom-grey** [comment] 2019-10-07 10:00
Strange i can't reproduce this. I don't suppose you would be able to share an example repo with this behaviour?

**Comment by jbourdale** [comment] 2019-10-07 11:56
https://github.com/jbourdale/tsdoc-plugin-markdown-fail

**Comment by tom-grey** [comment] 2019-10-07 13:54
Thanks for that. Could you set the version typedoc-plugin-markdown to 2.2.9 and try again please. I have removed the dependancy on Handlebars and it seems to fix the issue. Why it was only causing issue on this repo I am not too sure about though..

**Comment by jbourdale** [comment] 2019-10-07 14:08
Awesome, it works.
Thx for the reactivity!!

**Comment by rmakara** [comment] 2019-12-04 15:24
We're suffering from exactly the same issue. We tried to downgrade to `2.2.9` but it did not solve the problem. We tested it on 2 local environments and both are returning the same error message. I guess the path, which is being checked in the condition (`/src/theme.js`) is null in our case.

@tom-grey do you have some idea what could be a cause of the issue even after downgrading to `2.2.9`?

**Comment by arjunbalgovind** [comment] 2019-12-04 19:56
@rmakara I just faced the same issue. I tried downgrading TypeDoc to the version used by @jbourdale (0.14.0) and it works fine. I think the plugin doesn't seem to be working with the current version of TypeDoc (0.15.3).
@tom-grey any idea on what's throwing this error?

**Comment by tom-grey** [comment] 2019-12-04 20:47
@rmakara @arjunbalgovind  Thanks for the comments. I will re-open this. The cause is an issue with multiple handlebars instances being registered when the plugin assumes a global instance (a design flaw in this plugin). Most likely a local version of Handlebars has been installed which is a different version than typedoc. I will look at a fix for this scenario.

**Comment by tom-grey** [comment] 2019-12-05 00:40
@rmakara @arjunbalgovind  please try 2.2.13 ...

**Comment by rmakara** [comment] 2019-12-05 12:27
@tom-grey it works! Thank you for awesome, very quick fix. :) You are the best! :)

**Closed** 2019-12-05 14:06 UTC

**Comment by arjunbalgovind** [comment] 2019-12-05 19:18
@tom-grey you're amazing! Thanks for the great fix! I realized that there were some changes in TypeDoc 0.15.x that I really needed, so this is great :D
